#ifndef PYAV_COMPAT_H
#define PYAV_COMPAT_H
#define PYAV_VERSION 0.3.1
#define PYAV_VERSION_STR "0.3.1"
#define PYAV_COMMIT_STR "b'v0.3.1-46-g4f52260'"
#define PYAV_HAVE_LIBSWRESAMPLE 1
#define PYAV_HAVE_AV_CALLOC 1
#define PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP 1
#define PYAV_HAVE_AVFORMAT_ALLOC_OUTPUT_CONTEXT2 1
#define PYAV_HAVE_AVFORMAT_CLOSE_INPUT 1
#endif
